src/Entity/Chantier.php
<?php
namespace App\Entity;

use App\Repository\ChantierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChantierRepository::class)]
class Chantier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: "json", nullable: true)]
    private ?array $chantier_prerequis = [];

    #[ORM\Column]
    private ?int $effectif_requis = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'chantiersDirectes')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $chefChantier = null;

    #[ORM\OneToMany(mappedBy: 'chantier', targetEntity: Affectation::class, orphanRemoval: true)]
    private Collection $affectations;

    public function __construct()
    {
        $this->affectations = new ArrayCollection();
        $this->chantier_prerequis = [];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;
        return $this;
    }

    public function getChantierPrerequis(): ?array
    {
        return $this->chantier_prerequis ?? [];
    }

    public function setChantierPrerequis(?array $chantier_prerequis): static
    {
        $this->chantier_prerequis = $chantier_prerequis ?? [];
        return $this;
    }

    public function getChantierPrerequisAsString(): string
    {
        if (empty($this->chantier_prerequis)) {
            return 'Aucun prérequis';
        }
        return implode(', ', $this->chantier_prerequis);
    }

    public function getEffectifRequis(): ?int
    {
        return $this->effectif_requis;
    }

    public function setEffectifRequis(int $effectif_requis): static
    {
        $this->effectif_requis = $effectif_requis;
        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;
        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;
        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;
        return $this;
    }

    public function getChefChantier(): ?User
    {
        return $this->chefChantier;
    }

    public function setChefChantier(?User $chefChantier): static
    {
        $this->chefChantier = $chefChantier;
        return $this;
    }

    public function getAffectations(): Collection
    {
        return $this->affectations;
    }

    public function addAffectation(Affectation $affectation): static
    {
        if (!$this->affectations->contains($affectation)) {
            $this->affectations->add($affectation);
            $affectation->setChantier($this);
        }
        return $this;
    }

    public function removeAffectation(Affectation $affectation): static
    {
        if ($this->affectations->removeElement($affectation)) {
            if ($affectation->getChantier() === $this) {
                $affectation->setChantier(null);
            }
        }
        return $this;
    }

    public function getEffectifRestant(): int
    {
        $totalAffecte = 0;
        foreach ($this->getAffectations() as $affectation) {
            $equipe = $affectation->getEquipe();
            if ($equipe) {
                $totalAffecte += $equipe->getNombre();
            }
        }
        
        $restant = $this->getEffectifRequis() - $totalAffecte;
        return ($restant > 0) ? $restant : 0;
    }

    public function __toString(): string
    {
        return $this->nom ?? '';
    }
}

src/Entity/Equipe.php
<?php
namespace App\Entity;

use App\Repository\EquipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EquipeRepository::class)]
class Equipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_equipe = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'equipesDirectes')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $chefEquipe = null;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: User::class)]
    private Collection $users;

    #[ORM\OneToMany(mappedBy: 'equipe', targetEntity: Affectation::class, orphanRemoval: true)]
    private Collection $affectations;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->affectations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEquipe(): ?string
    {
        return $this->nom_equipe;
    }

    public function setNomEquipe(string $nom_equipe): static
    {
        $this->nom_equipe = $nom_equipe;
        return $this;
    }

    public function getChefEquipe(): ?User
    {
        return $this->chefEquipe;
    }

    public function setChefEquipe(?User $chefEquipe): static
    {
        $this->chefEquipe = $chefEquipe;
        return $this;
    }

    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setEquipe($this);
        }
        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            if ($user->getEquipe() === $this) {
                $user->setEquipe(null);
            }
        }
        return $this;
    }

    public function getAffectations(): Collection
    {
        return $this->affectations;
    }

    public function addAffectation(Affectation $affectation): static
    {
        if (!$this->affectations->contains($affectation)) {
            $this->affectations->add($affectation);
            $affectation->setEquipe($this);
        }
        return $this;
    }

    public function removeAffectation(Affectation $affectation): static
    {
        if ($this->affectations->removeElement($affectation)) {
            if ($affectation->getEquipe() === $this) {
                $affectation->setEquipe(null);
            }
        }
        return $this;
    }

    public function getNombre(): int
    {
        return $this->users->count();
    }

    public function getCompetences(): array
    {
        $competences = [];
        foreach ($this->users as $user) {
            foreach ($user->getUserCompetences() as $userCompetence) {
                $competence = $userCompetence->getCompetence();
                if ($competence && $competence->isActif()) {
                    $competences[$competence->getId()] = $competence->getNom();
                }
            }
        }
        return array_values($competences);
    }

    public function __toString(): string
    {
        return $this->nom_equipe ?? '';
    }
}

src/Controller/ChantierController.php
<?php
namespace App\Controller;

use App\Entity\Chantier;
use App\Form\ChantierType;
use App\Repository\ChantierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/chantier')]
class ChantierController extends AbstractController
{
    #[Route('/', name: 'app_chantier_index', methods: ['GET'])]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function index(ChantierRepository $chantierRepository): Response
    {
        $user = $this->getUser();
        
        if ($user->isAdmin()) {
            $chantiers = $chantierRepository->findAll();
        } else {
            $chantiers = [];
            if ($user->getEquipe()) {
                foreach ($user->getEquipe()->getAffectations() as $affectation) {
                    $chantier = $affectation->getChantier();
                    if ($chantier->getChantierPrerequis() === null) {
                        $chantier->setChantierPrerequis([]);
                    }
                    $chantiers[] = $chantier;
                }
            }
        }

        foreach ($chantiers as $chantier) {
            if ($chantier->getChantierPrerequis() === null) {
                $chantier->setChantierPrerequis([]);
            }
        }

        return $this->render('chantier/index.html.twig', [
            'chantiers' => $chantiers,
        ]);
    }

    #[Route('/new', name: 'app_chantier_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $chantier = new Chantier();
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('imageFile')->getData();
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Erreur lors de l\'upload de l\'image.');
                }

                $chantier->setImage($newFilename);
            }

            if ($chantier->getChantierPrerequis() === null) {
                $chantier->setChantierPrerequis([]);
            }

            $entityManager->persist($chantier);
            $entityManager->flush();

            $this->addFlash('success', 'Chantier créé avec succès !');
            return $this->redirectToRoute('app_chantier_index');
        }

        return $this->render('chantier/new.html.twig', [
            'chantier' => $chantier,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_chantier_show', methods: ['GET'])]
    #[IsGranted('IS_AUTHENTICATED_FULLY')]
    public function show(Chantier $chantier): Response
    {
        $user = $this->getUser();
        
        if (!$user->isAdmin()) {
            $hasAccess = false;
            if ($user->getEquipe()) {
                foreach ($user->getEquipe()->getAffectations() as $affectation) {
                    if ($affectation->getChantier() === $chantier) {
                        $hasAccess = true;
                        break;
                    }
                }
            }
            
            if (!$hasAccess) {
                throw $this->createAccessDeniedException('Vous n\'avez pas accès à ce chantier.');
            }
        }

        if ($chantier->getChantierPrerequis() === null) {
            $chantier->setChantierPrerequis([]);
        }

        return $this->render('chantier/show.html.twig', [
            'chantier' => $chantier,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_chantier_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Chantier $chantier, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(ChantierType::class, $chantier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $imageFile */
            $imageFile = $form->get('imageFile')->getData();
            if ($imageFile) {
                $originalFilename = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );

                    if ($chantier->getImage()) {
                        $oldImagePath = $this->getParameter('images_directory') . '/' . $chantier->getImage();
                        if (file_exists($oldImagePath)) {
                            unlink($oldImagePath);
                        }
                    }

                    $chantier->setImage($newFilename);
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Erreur lors de l\'upload de l\'image.');
                }
            }

            if ($chantier->getChantierPrerequis() === null) {
                $chantier->setChantierPrerequis([]);
            }

            $entityManager->flush();

            $this->addFlash('success', 'Chantier mis à jour avec succès !');
            return $this->redirectToRoute('app_chantier_index');
        }

        return $this->render('chantier/edit.html.twig', [
            'chantier' => $chantier,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_chantier_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Chantier $chantier, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $chantier->getId(), $request->request->get('_token'))) {
            if ($chantier->getImage()) {
                $imagePath = $this->getParameter('images_directory') . '/' . $chantier->getImage();
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
            }

            $entityManager->remove($chantier);
            $entityManager->flush();

            $this->addFlash('success', 'Chantier supprimé avec succès !');
        }

        return $this->redirectToRoute('app_chantier_index');
    }
}

templates/chantier/_delete_form.html.twig
<form method="post" action="{{ path('app_chantier_delete', {'id': chantier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ chantier.id) }}">
    <button class="btn">Delete</button>
</form>

templates/chantier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le Chantier{% endblock %}

{% block body %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Modifier le Chantier: {{ chantier.nom }}</h2>
    
    <div class="card shadow-lg border-0">
        <div class="card-body">
            {{ include('chantier/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
        </div>
    </div>
    
    <div class="mt-4 text-center">
        <a href="{{ path('app_chantier_show', {'id': chantier.id}) }}" class="btn btn-info me-2">
            <i class="fas fa-eye"></i> Voir le chantier
        </a>
        <a href="{{ path('app_chantier_index') }}" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Retour à la liste
        </a>
    </div>
</div>

{% block javascripts %}
<script>
document.addEventListener("DOMContentLoaded", function () {
    let dateDebut = document.getElementById("{{ form.date_debut.vars.id }}");
    let dateFin = document.getElementById("{{ form.date_fin.vars.id }}");
    
    if (dateDebut && dateFin) {
        dateFin.addEventListener("change", function () {
            dateDebut.setAttribute("max", dateFin.value);
        });
        
        dateDebut.addEventListener("change", function () {
            if (dateDebut.value && dateFin.value && dateDebut.value > dateFin.value) {
                alert("La date de début ne peut pas être après la date de fin !");
                dateDebut.value = "";
            }
        });
    }
});
</script>
{% endblock %}
{% endblock %}

templates/chantier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Chantiers{% endblock %}

{% block body %}
<div class="container mt-4">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h1>
                    {% if app.user.isAdmin %}
                        Gestion des Chantiers
                    {% else %}
                        Mes Chantiers
                    {% endif %}
                </h1>
                {% if app.user.isAdmin %}
                    <a href="{{ path('app_chantier_new') }}" class="btn btn-primary">
                        <i class="fas fa-plus"></i> Nouveau Chantier
                    </a>
                {% endif %}
            </div>

            {% for message in app.flashes('success') %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% endfor %}

            {% if chantiers|length > 0 %}
                <div class="row">
                    {% for chantier in chantiers %}
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card h-100">
                                {% if chantier.image %}
                                    <img src="{{ asset('uploads/images/' ~ chantier.image) }}" 
                                         class="card-img-top" style="height: 200px; object-fit: cover;">
                                {% endif %}
                                
                                <div class="card-header">
                                    <h5 class="mb-0">{{ chantier.nom }}</h5>
                                </div>
                                
                                <div class="card-body">
                                    <div class="mb-2">
                                        <strong>Période:</strong><br>
                                        <small>{{ chantier.dateDebut|date('d/m/Y') }} - {{ chantier.dateFin|date('d/m/Y') }}</small>
                                    </div>

                                    <div class="mb-2">
                                        <strong>Effectif requis:</strong>
                                        <span class="badge bg-primary">{{ chantier.effectifRequis }}</span>
                                    </div>

                                    {% if chantier.chefChantier %}
                                        <div class="mb-2">
                                            <strong>Chef de chantier:</strong><br>
                                            <span class="badge bg-warning">{{ chantier.chefChantier.nom }}</span>
                                        </div>
                                    {% endif %}

                                    <div class="mb-2">
                                        <strong>Compétences requises:</strong><br>
                                        {% if chantier.chantierPrerequis is defined and chantier.chantierPrerequis is not empty %}
                                            <div style="max-height: 50px; overflow: hidden;">
                                                {% for competence in chantier.chantierPrerequis|slice(0, 2) %}
                                                    <span class="badge bg-secondary me-1 mb-1">{{ competence }}</span>
                                                {% endfor %}
                                                {% if chantier.chantierPrerequis|length > 2 %}
                                                    <span class="badge bg-info">+{{ chantier.chantierPrerequis|length - 2 }}</span>
                                                {% endif %}
                                            </div>
                                        {% else %}
                                            <span class="text-muted">Aucune</span>
                                        {% endif %}
                                    </div>

                                    {% if app.user.isAdmin %}
                                        <div class="mb-2">
                                            <strong>Effectif restant:</strong>
                                            <span class="badge bg-{{ chantier.effectifRestant > 0 ? 'success' : 'danger' }}">
                                                {{ chantier.effectifRestant }}
                                            </span>
                                        </div>
                                    {% endif %}
                                </div>
                                
                                <div class="card-footer">
                                    <div class="btn-group w-100" role="group">
                                        <a href="{{ path('app_chantier_show', {'id': chantier.id}) }}" 
                                           class="btn btn-outline-info btn-sm">
                                            <i class="fas fa-eye"></i> Voir
                                        </a>
                                        {% if app.user.isAdmin %}
                                            <a href="{{ path('app_chantier_edit', {'id': chantier.id}) }}" 
                                               class="btn btn-outline-warning btn-sm">
                                                <i class="fas fa-edit"></i> Modifier
                                            </a>
                                            {% if chantier.effectifRestant > 0 %}
                                                <a href="{{ path('app_affectation_new', {'id': chantier.id}) }}" 
                                                   class="btn btn-outline-success btn-sm">
                                                    <i class="fas fa-plus"></i> Affecter
                                                </a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="text-center py-5">
                    <i class="fas fa-building fa-3x text-muted mb-3"></i>
                    <p class="text-muted">
                        {% if app.user.isAdmin %}
                            Aucun chantier trouvé.
                        {% else %}
                            Aucun chantier assigné pour le moment.
                        {% endif %}
                    </p>
                    {% if app.user.isAdmin %}
                        <a href="{{ path('app_chantier_new') }}" class="btn btn-primary">Créer le premier chantier</a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/chantier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ chantier.nom }}{% endblock %}

{% block body %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="mb-0">{{ chantier.nom }}</h3>
                    {% if app.user.isAdmin %}
                        <div class="btn-group" role="group">
                            <a href="{{ path('app_chantier_edit', {'id': chantier.id}) }}" 
                               class="btn btn-warning btn-sm">
                                <i class="fas fa-edit"></i> Modifier
                            </a>
                            {% if chantier.effectifRestant > 0 %}
                                <a href="{{ path('app_affectation_new', {'id': chantier.id}) }}" 
                                   class="btn btn-success btn-sm">
                                    <i class="fas fa-plus"></i> Affecter une équipe
                                </a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                
                {% if chantier.image %}
                    <img src="{{ asset('uploads/images/' ~ chantier.image) }}" 
                         class="card-img-top" style="height: 300px; object-fit: cover;">
                {% endif %}
                
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>Informations générales</h5>
                            <table class="table table-borderless">
                                <tr>
                                    <td><strong>Période:</strong></td>
                                    <td>{{ chantier.dateDebut|date('d/m/Y') }} - {{ chantier.dateFin|date('d/m/Y') }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Effectif requis:</strong></td>
                                    <td><span class="badge bg-primary">{{ chantier.effectifRequis }}</span></td>
                                </tr>
                                <tr>
                                    <td><strong>Effectif restant:</strong></td>
                                    <td>
                                        <span class="badge bg-{{ chantier.effectifRestant > 0 ? 'success' : 'danger' }}">
                                            {{ chantier.effectifRestant }}
                                        </span>
                                    </td>
                                </tr>
                                {% if chantier.chefChantier %}
                                    <tr>
                                        <td><strong>Chef de chantier:</strong></td>
                                        <td><span class="badge bg-warning">{{ chantier.chefChantier.nom }}</span></td>
                                    </tr>
                                {% endif %}
                            </table>
                        </div>
                        
                        <div class="col-md-6">
                            <h5>Compétences requises</h5>
                            {% if chantier.chantierPrerequis is not empty %}
                                <div class="mb-3">
                                    {% for competence in chantier.chantierPrerequis %}
                                        <span class="badge bg-secondary me-1 mb-1">{{ competence }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <p class="text-muted">Aucune compétence spécifique requise</p>
                            {% endif %}
                        </div>
                    </div>
                    
                    {% if chantier.affectations|length > 0 %}
                        <hr>
                        <h5>Équipes affectées</h5>
                        <div class="row">
                            {% for affectation in chantier.affectations %}
                                <div class="col-md-6 mb-3">
                                    <div class="card border-success">
                                        <div class="card-body">
                                            <h6 class="card-title">{{ affectation.equipe.nomEquipe }}</h6>
                                            <p class="card-text">
                                                <strong>Membres:</strong> {{ affectation.equipe.nombre }}<br>
                                                {% if affectation.equipe.chefEquipe %}
                                                    <strong>Chef:</strong> {{ affectation.equipe.chefEquipe.nom }}<br>
                                                {% endif %}
                                                <strong>Compétences:</strong>
                                                {% set competencesEquipe = affectation.equipe.competences %}
                                                {% if competencesEquipe is not empty %}
                                                    {{ competencesEquipe|join(', ') }}
                                                {% else %}
                                                    <span class="text-muted">Aucune</span>
                                                {% endif %}
                                            </p>
                                            <a href="{{ path('app_affectation_show', {'id': affectation.id}) }}" 
                                               class="btn btn-outline-success btn-sm">
                                                <i class="fas fa-eye"></i> Voir l'affectation
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="alert alert-info mt-3">
                            <i class="fas fa-info-circle"></i> 
                            Aucune équipe n'est encore affectée à ce chantier.
                            {% if app.user.isAdmin %}
                                <a href="{{ path('app_affectation_new', {'id': chantier.id}) }}" 
                                   class="btn btn-success btn-sm ms-2">
                                    Affecter une équipe
                                </a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                
                <div class="card-footer">
                    <a href="{{ path('app_chantier_index') }}" class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i> Retour à la liste
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}